package com.ekenya.rnd.common.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "user")
data class UserDetails(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Autogenerated primary key
    val email: String,
    val firstName: String,
    val lastName: String,
    val password: String,
    val phoneNumber: String
)
